# Generated by Django 5.0 on 2023-12-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiptDescription', models.CharField(max_length=100)),
                ('receiptType', models.CharField(choices=[('1', '薪資'), ('2', '薪資所得'), ('3', '兼職'), ('4', '獎金'), ('5', '發票/彩券收入'), ('6', '租金'), ('7', '優惠回饋'), ('8', '股利'), ('9', '投資獲利'), ('10', '保險'), ('11', '退休金'), ('12', '提款'), ('13', '贈與'), ('14', '還錢')], max_length=255)),
                ('receiptNumber', models.IntegerField()),
                ('recieptDate', models.DateField()),
            ],
        ),
    ]
