# Generated by Django 5.0 on 2023-12-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenseDescription', models.CharField(max_length=100)),
                ('expenseType', models.CharField(choices=[('1', '飲食'), ('2', '服飾'), ('3', '住家'), ('4', '交通'), ('5', '學習'), ('6', '休閒娛樂'), ('7', '購物'), ('8', '醫療'), ('9', '現金消費'), ('10', '保險'), ('11', '費用/手續費'), ('12', '稅金'), ('13', '繳費'), ('14', '娛樂')], max_length=255)),
                ('expenseNumber', models.IntegerField()),
                ('expenseDate', models.DateField()),
            ],
        ),
    ]
