# Generated by Django 5.0 on 2023-12-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_ledgerexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerexpense',
            name='expenseType',
            field=models.CharField(choices=[('飲食', '飲食'), ('服飾', '服飾'), ('住家', '住家'), ('交通', '交通'), ('學習', '學習'), ('休閒娛樂', '休閒娛樂'), ('購物', '購物'), ('醫療', '醫療'), ('現金消費', '現金消費'), ('保險', '保險'), ('費用/手續費', '費用/手續費'), ('稅金', '稅金'), ('繳費', '繳費'), ('娛樂', '娛樂')], max_length=255),
        ),
        migrations.AlterField(
            model_name='ledgerincome',
            name='receiptType',
            field=models.CharField(choices=[('薪資', '薪資'), ('薪資所得', '薪資所得'), ('兼職', '兼職'), ('獎金', '獎金'), ('發票/彩券收入', '發票/彩券收入'), ('租金', '租金'), ('優惠回饋', '優惠回饋'), ('股利', '股利'), ('投資獲利', '投資獲利'), ('保險', '保險'), ('退休金', '退休金'), ('提款', '提款'), ('贈與', '贈與'), ('還錢', '還錢')], max_length=255),
        ),
    ]
